# Time Series models are used for forecasting values by analyzing the historical data listed 
# in the time order. 

# Demonstrate time series model by using a dataset for production units.

# Read .csv file
my_data <- read.csv(file.choose()) # use ProductionUnits.csv

# Check file
View(my_data)

# Index data by using the time series (ts) function
## The ts() function will convert numeric vector into R time series object.
## The format is ts(vector, start=, end=, frequency=) where start and end are the 
## times of the first and last observation and frequency refers to the number of occurrences
## in this case,since we are doing it by month, the frequency is 12
time_units <- ts(my_data$Units, start=c(2000, 1), end=c(2009,12), frequency=12)

# Print to see the indexed data
print(time_units)

## See the trend or seasonality of indexed data
## col = color; lwd = line width
plot(time_units,col='blue',lwd=2) # plot is a general function for R objects

# Let's look at a couple of techniques to forecast the # of units for the next 12 months


# Moving average 
## Gives an overall idea of the trends in a data set based upon average of the numbers
## Compute average based upon previous year and plot graph
## Convert data values to log scale to eliminate seasonality and trend
time_units2 <- log(time_units)

## Use aggregate function to calculate moving average
## Aggregate is a generic function for data frames and time series
moving_avg <- aggregate(time_units,FUN=mean) # Function to calculate summary statistics
plot(time_units,col='blue',lwd=2) # overall trend, same as line 19; col = color; lwd = line width
lines(moving_avg,col='green',lwd=2) # trend line 


# Decomposition
## Separates historical data into different components and uses them to create a forecast 
## Seasonal decomposition of time series (stl) function decomposes a time series 
## into seasonal, trend and irregular components
stl_units2 <- stl(time_units2, s.window = 'periodic' ) #s.window is for seasonal extraction

## Find accuracy for the model generated by the stl function
## Install forecast package
install.packages("forecast")

##Load forecast library
library(forecast)

## Calculate accuracy
accuracy(forecast(stl_units2, h=12)) # h is number of period for forecasting
## Recommend to use Root Mean Square Error (RMSE)

## Plot stl components generated for each variable
plot(stl_units2,lwd=1)

## Use forecast package to predict the variables
require(forecast)
forecast(stl_units2, h=12)

## Plot the forecast based upon stl function
plot(forecast(stl_units2, h=12)) # log transformation


# Exponential Smoothing
## Way to smooth out time-series data
## Recent observations are given relatively more weight in forecasting than the older observations
## Use Exponential Smoothing State Space Model (ets) 
ets_units2 <- ets(time_units2)

## Find accuracy for the model generated by the ets function
accuracy(ets_units2$fitted,time_units2) # Gauge accuracy with RMSE

## Forecast using ets output
forecast(ets_units2,h=12)

## Plot the forecasted values produced by using the ets function 
plot(forecast(ets_units2,h=12))


# Autoregressive Integrated Moving Averages (ARIMA)
## Accounts time series data in pattern of change, rate of change and 
## noise between consecutive data points
## ARIMA is part of the forecast package
arima_units <- auto.arima(time_units2)

## Find accuracy for the model generated by the arima function
accuracy(arima_units) # Gauge accuracy with RMSE`                                                                                                                                                                                                                                                                                                      `

## Forecast using arima output
forecast(arima_units,h=12)

## Plot the forecast based upon arima function
plot(forecast(arima_units,h=12))

